apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Update cluster name, region, and eks version if needed
metadata:
  name: eks-p4de-odcr-vpc
  version: "1.28"
  region: PLACEHOLDER_AWS_REGION

# Substitute vpc and subnet ids below
vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    public:
      public-one:
        id: PLACEHOLDER_SUBNET_PUBLIC_1
      public-two:
        id: PLACEHOLDER_SUBNET_PUBLIC_2
    private:
      private-one:
        id: PLACEHOLDER_SUBNET_PRIVATE_1
      private-two:
        id: PLACEHOLDER_SUBNET_PRIVATE_2

# Fully-managed nodegroups
managedNodeGroups:

  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # Update capacityReservationID below
  # Specify the subnet id matching the capacity reservation
  - name: p4de-odcr-vpc
    instanceType: p4de.24xlarge
    instancePrefix: p4de-odcr-vpc
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 500
    subnets:
    - PLACEHOLDER_SUBNET_PRIVATE_2
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "PLACEHOLDER_CAPACITY_RESERVATION_ID"
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
