apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Update cluster name, region, and eks version if needed
metadata:
  name: eks-g4dn-vpc
  version: "1.27"
  region: us-east-1

# Substitute vpc and subnet ids below
vpc:
  id: vpc-xxxxxxxxxxxxxxxxx
  subnets:
    public:
      public-one:
        id: subnet-xxxxxxxxxxxxxxx11
      public-two:
        id: subnet-xxxxxxxxxxxxxxx12
    private:
      private-one:
        id: subnet-xxxxxxxxxxxxxxx21
      private-two:
        id: subnet-xxxxxxxxxxxxxxx22

# Fully-managed nodegroups
managedNodeGroups:

  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # Update capacityReservationID below
  # specify the subnet id corresponding to the capacity reservation
  - name: g4dn
    instanceType: g4dn.8xlarge
    instancePrefix: g4dn-vpc
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 500
    subnets:
    - subnet-xxxxxxxxxxxxxxx22
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
