apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-g4dn-vpc
  version: "1.27"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1c

managedNodeGroups:
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
  - name g4dn
    instanceType: g4dn.metal
    instancePrefix: g4dn-vpc
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 500
    availabilityZones: ["us-east-1c"]
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
